In [1]:
import numpy as np

In [2]:
l=[1,2,3]
arr=np.array(l)
arr

array([1, 2, 3])

In [3]:
l=[[1,2,3],[4,5,6]]
arr1=np.array(l)
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(2,10,3)

array([2, 5, 8])

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [12]:
np.random.rand(3,5) #random numbers between 0 a 1

array([[0.90446058, 0.51171881, 0.06251415, 0.17301604, 0.07419261],
       [0.81492563, 0.62502463, 0.68368535, 0.04799426, 0.26364212],
       [0.62928237, 0.31224391, 0.59009028, 0.85254491, 0.24645478]])

In [13]:
np.random.randn(3,5)

array([[ 0.43171353,  1.30128283,  1.06118578,  1.20679979, -0.37794097],
       [-1.17580273, -1.48473071, -0.00185465,  0.55015121,  0.66877887],
       [-1.32155027,  0.40997658, -0.8572277 ,  0.20141922,  0.1102467 ]])

In [14]:
np.random.randint(1,100)#100 cannot e the output

54

In [15]:
np.random.randint(1,10,100)

array([1, 6, 9, 9, 8, 4, 1, 6, 8, 4, 1, 2, 8, 3, 9, 4, 1, 6, 4, 6, 9, 8,
       7, 5, 8, 7, 4, 4, 5, 1, 8, 1, 3, 6, 4, 9, 6, 4, 5, 7, 7, 8, 4, 7,
       1, 6, 4, 5, 1, 4, 4, 5, 6, 7, 6, 4, 1, 2, 6, 6, 4, 1, 6, 5, 8, 7,
       8, 4, 5, 8, 6, 2, 1, 7, 9, 6, 1, 8, 5, 9, 6, 9, 5, 6, 8, 3, 2, 2,
       8, 9, 3, 2, 7, 5, 6, 4, 8, 2, 5, 7])

In [16]:
arr=np.arange(1,31)

In [17]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [18]:
arr.shape

(30,)

In [19]:
arr.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [20]:
arr.max()

30

In [21]:
arr.argmax()  #index at whihc the max value is present

29

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
arr[:3]=20

In [25]:
arr

array([20, 20, 20,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

# twodimensional array

In [26]:
arr=np.arange(1,31)

In [29]:
arr=arr.reshape(6,5)

In [30]:
arr[1,4]

10

In [35]:
arr[:,(1,2)]

array([[ 4,  6],
       [14, 16],
       [24, 26],
       [34, 36],
       [44, 46],
       [54, 56]])

In [31]:
arr+=arr

In [32]:
#all above done are applicible to 2 dim array also
#ndim

In [33]:
np.unique(arr)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [34]:
np.exp(arr)

array([[7.38905610e+00, 5.45981500e+01, 4.03428793e+02, 2.98095799e+03,
        2.20264658e+04],
       [1.62754791e+05, 1.20260428e+06, 8.88611052e+06, 6.56599691e+07,
        4.85165195e+08],
       [3.58491285e+09, 2.64891221e+10, 1.95729609e+11, 1.44625706e+12,
        1.06864746e+13],
       [7.89629602e+13, 5.83461743e+14, 4.31123155e+15, 3.18559318e+16,
        2.35385267e+17],
       [1.73927494e+18, 1.28516001e+19, 9.49611942e+19, 7.01673591e+20,
        5.18470553e+21],
       [3.83100800e+22, 2.83075330e+23, 2.09165950e+24, 1.54553894e+25,
        1.14200739e+26]])

In [36]:
np.sqrt(arr)

array([[1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766],
       [3.46410162, 3.74165739, 4.        , 4.24264069, 4.47213595],
       [4.69041576, 4.89897949, 5.09901951, 5.29150262, 5.47722558],
       [5.65685425, 5.83095189, 6.        , 6.164414  , 6.32455532],
       [6.4807407 , 6.63324958, 6.78232998, 6.92820323, 7.07106781],
       [7.21110255, 7.34846923, 7.48331477, 7.61577311, 7.74596669]])

In [37]:
np.log(arr)

array([[0.69314718, 1.38629436, 1.79175947, 2.07944154, 2.30258509],
       [2.48490665, 2.63905733, 2.77258872, 2.89037176, 2.99573227],
       [3.09104245, 3.17805383, 3.25809654, 3.33220451, 3.40119738],
       [3.4657359 , 3.52636052, 3.58351894, 3.63758616, 3.68887945],
       [3.73766962, 3.78418963, 3.8286414 , 3.87120101, 3.91202301],
       [3.95124372, 3.98898405, 4.02535169, 4.06044301, 4.09434456]])

In [38]:
np.square(arr)

array([[   4,   16,   36,   64,  100],
       [ 144,  196,  256,  324,  400],
       [ 484,  576,  676,  784,  900],
       [1024, 1156, 1296, 1444, 1600],
       [1764, 1936, 2116, 2304, 2500],
       [2704, 2916, 3136, 3364, 3600]])

In [40]:
np.var(arr)

299.6666666666667

In [41]:
np.mean(arr)

31.0

In [42]:
arr=np.random.randn(3,4)

In [43]:
np.round(arr,decimals=2)

array([[ 2.68,  0.8 ,  0.8 , -0.57],
       [-0.34, -0.99, -0.88, -1.74],
       [ 1.99, -0.45,  0.21,  0.98]])